### ISSUE TITLE
Install Error: 'failed to open stream: No such file or directory'

### ISSUE THREAD

**Issue by samparkewolfe** [matt-allan/hours#38]
**Describe the bug**
Followed install instructions but got the following error when running the final command

Sams-MBP-2:~ samparkewolfe$ hours --version

In Filesystem.php line 122:

  file_put_contents(/Users/samparkewolfe/.local/share/Hours/database.sqlite): failed to open stream: No such file or directory

**To Reproduce**
Just follow the installation instructions.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version: High Sierra

**Additional context**
I have the requested version of php and sqlite3 is an extention.

**Comment by matt-allan** [comment]
Thanks for the bug report.

Apparently Laravel's `File` class doesn't create the directory automatically like the `Storage` class. I think we need to add a call to `File::ensureDirectoryExists(dirname($databasePath))` [here](https://github.com/matt-allan/hours/blob/master/app/Events/InitializeDatabase.php#L30).

**Comment by peter279k** [comment]
It seems that the `File::ensureDirectoryExists()` method is available since `illuminate/filesystem` `v6.13.0` version. Here is the [reference](https://laravel-news.com/laravel-6-13-0).

But this package still support `v5.8.x` version about minimum.

If we want to accomplish this issue with `File::ensureDirectoryExists` method, I think we need to consider upgrading the `illuminate/database` dependency.

Otherwise we can only use `File::isDirectory(dirname($databasePath));` and create non-existed directory recursively by ourselves.

@matt-allan, what do you think about this?

**Comment by matt-allan** [comment]
Thanks @peter279k, upgrading dependencies would be great.

**Comment by matt-allan** [comment]
Hey @samparkewolfe, this issue should be fixed in the v0.2.0 release thanks to @peter279k. You can follow the installation guide in the README to download the new version.

Thanks for contributing everyone!
